### ISSUE TITLE
Schema dati (schemas) nel file definizione swagger v1 

### ISSUE THREAD

**Issue by loreV** [APT-Servizi/openapi-ert#3]
Attualmente nel file di definizione swagger v1 manca lo schema dati (schemas) che sarebbe molto utile per poter permettere più facili integrazione di altri sistemi con ERT. 

Aggiungere questo schema dati.

**Comment by wetfire2k** [comment]
Lo schema dati, non essendo un requisito obbligatorio non è una priorità nel breve periodo.
Valutiamo se metterlo in cantiere con le attività della piattaforma di marzo 2023.
